house_pricing: 
  train_dataset: D:\Projects\spbu-ai-fundamentals\Datasets\house_prices\train.csv
  test_dataset: D:\Projects\spbu-ai-fundamentals\Datasets\house_prices\test.csv

classification:
  wdbc: D:\Projects\spbu-ai-fundamentals\Datasets\classification\data.csv
  mushrooms: D:\Projects\spbu-ai-fundamentals\Datasets\classification\mushrooms.csv

clustering:
  flowcytometry: D:\Projects\spbu-ai-fundamentals\Datasets\flow_cytometry
